services:
  app:
    build: .
    container_name: transcribeforge.hiltmann.cloud
    restart: always
    env_file:
      - .env
    volumes:
      - ./youtube-cookies.txt:/app/youtube-cookies.txt:ro
      - ./yt-dlp-cache:/root/.cache/yt-dlp
    networks:
      - n8n_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=n8n_default"
      - "traefik.http.routers.transcribeforge.rule=Host(`transcribeforge.hiltmann.cloud`)"
      - "traefik.http.routers.transcribeforge.entrypoints=websecure"
      - "traefik.http.routers.transcribeforge.tls=true"
      - "traefik.http.routers.transcribeforge.tls.certresolver=mytlschallenge"
      - "traefik.http.services.transcribeforge.loadbalancer.server.port=3001"

networks:
  n8n_default:
    external: true
